var utilitiesController={
	activeSelected: function(elems,elem){
		dvn.each(elems,function(i,v){
			dvn(v).removeClass('selected');
		});
		dvn(elem).addClass('selected');
	}
};

var estadosMexico=[
			 'Aguascalientes',
			 'Ciudad de México',
			 'Baja California',
			 'Baja California Sur',
			 'Campeche',
			 'Chiapas',
			 'Durango',
			 'Coahuila de Zaragoza',
			 'San Luis Potosí',
			 'Estado de México',
			 'Guanajuato',
			 'Guerrero',
			 'Colima',
			 'Hidalgo',
			 'Jalisco',
			 'Michoacán de Ocampo',
			 'Morelos',
			 'Nayarit',
			 'Nuevo León',
			 'Sin Localidad',
			 'Oaxaca',
			 'Puebla',
			 'Querétaro',
			 'Quintana Roo',
			 'Sinaloa',
			 'Tabasco',
			 'Tamaulipas',
			 'Tlaxcala',
			 'Veracruz',
			 'Sonora',
			 'Chihuahua',
			 'Yucatán',
			 'Zacatecas'
		];

var edosMx=[
			 {valor:1,name:'Aguascalientes'},
			 {valor:2,name:'Ciudad de México'},
			 {valor:3,name:'Baja California'},
			 {valor:4,name:'Baja California Sur'},
			 {valor:5,name:'Campeche'},
			 {valor:6,name:'Chiapas'},
			 {valor:7,name:'Durango'},
			 {valor:8,name:'Coahuila de Zaragoza'},
			 {valor:9,name:'San Luis Potosí'},
			 {valor:10,name:'Estado de México'},
			 {valor:11,name:'Guanajuato'},
			 {valor:12,name:'Guerrero'},
			 {valor:13,name:'Colima'},
			 {valor:14,name:'Hidalgo'},
			 {valor:15,name:'Jalisco'},
			 {valor:16,name:'Michoacán de Ocampo'},
			 {valor:17,name:'Morelos'},
			 {valor:18,name:'Nayarit'},
			 {valor:19,name:'Nuevo León'},
			 {valor:20,name:'Sin Localidad'},
			 {valor:21,name:'Oaxaca'},
			 {valor:22,name:'Puebla'},
			 {valor:23,name:'Querétaro'},
			 {valor:24,name:'Quintana Roo'},
			 {valor:25,name:'Sinaloa'},
			 {valor:26,name:'Tabasco'},
			 {valor:27,name:'Tamaulipas'},
			 {valor:28,name:'Tlaxcala'},
			 {valor:29,name:'Veracruz'},
			 {valor:30,name:'Sonora'},
			 {valor:31,name:'Chihuahua'},
			 {valor:32,name:'Yucatán'},
			 {valor:33,name:'Zacatecas'}
		];
var paises = [
{pais:'Afganistán',                                capital: 'Kabul' ,                                                                       continente:'Asia'},
{pais:'Albania',                                   capital: 'Tirana' ,                                                                      continente:'Europa'},
{pais:'Alemania',                                  capital: 'Berlín' ,                                                                      continente:'Europa'},
{pais:'Andorra',                                   capital: 'Andorra la Vieja' ,                                                            continente:'Europa'},
{pais:'Angola',                                    capital: 'Luanda' ,                                                                      continente:'África'},
{pais:'Antigua',                                   capital: 'y Barbuda	Saint John' ,                                                       continente:'América'},
{pais:'Arabia',                                    capital: 'Saudita / Arabia Saudí	Riad' ,                                                 continente:'Asia'},
{pais:'Argelia',                                   capital: 'Argel' ,                                                                       continente:'África'},
{pais:'Argentina',                                 capital: 'Buenos Aires' ,                                                                continente:'América'},
{pais:'Armenia',                                   capital: 'Ereván	Asia' ,                                                                 continente:'Europa'},
{pais:'Australia',                                 capital: 'Canberra' ,                                                                    continente:'Oceanía'},
{pais:'Austria',                                   capital: 'Viena' ,                                                                       continente:'Europa'},
{pais:'Azerbaiyán',                                capital: 'Bakú	Asia' ,                                                                 continente:'Europa'},
{pais:'Bahamas',                                   capital: 'Nasáu' ,                                                                       continente:'América'},
{pais:'Bangladés',                                 capital: 'Daca' ,                                                                        continente:'Asia'},
{pais:'Barbados',                                  capital: 'Bridgetown' ,                                                                  continente:'América'},
{pais:'Baréin',                                    capital: 'Manama' ,                                                                      continente:'Asia'},
{pais:'Bélgica',                                   capital: 'Bruselas' ,                                                                    continente:'Europa'},
{pais:'Belice',                                    capital: 'Belmopán' ,                                                                    continente:'América'},
{pais:'Bielorrusia',                               capital: 'Minsk' ,                                                                       continente:'Europa'},
{pais:'Benín',                                     capital: 'Porto Novo3​' ,                                                                continente:'África'},
{pais:'Birmania',                                  capital: '/ Myanmar	Naipyidó' ,                                                         continente:'Asia'},
{pais:'Bolivia',                                   capital: 'Sucre5​' ,                                                                     continente:'América'},
{pais:'Bosnia y Herzegovina / Bosnia-Herzegovina', capital: 'Sarajevo' ,                                                                    continente:'Europa'},
{pais:'Botsuana',                                  capital: 'Gaborone' ,                                                                    continente:'África'},
{pais:'Brasil',                                    capital: 'Brasilia' ,                                                                    continente:'América'},
{pais:'Brunéi',                                    capital: 'Bandar Seri Begawan' ,                                                         continente:'Asia'},
{pais:'Bulgaria',                                  capital: 'Sofía' ,                                                                       continente:'Europa'},
{pais:'Burkina Faso',                              capital: 'Uagadugú' ,                                                                    continente:'África'},
{pais:'Burundi',                                   capital: 'Gitega6​' ,                                                                    continente:'África'},
{pais:'Bután',                                     capital: 'Timbu' ,                                                                       continente:'Asia'},
{pais:'Cabo',                                      capital: 'Verde	Praia' ,                                                                continente:'África'},
{pais:'Camboya',                                   capital: 'Nom Pen' ,                                                                     continente:'Asia'},
{pais:'Camerún',                                   capital: 'Yaundé' ,                                                                      continente:'África'},
{pais:'Canadá',                                    capital: 'Ottawa' ,                                                                      continente:'América'},
{pais:'Catar',                                     capital: 'Doha' ,                                                                        continente:'Asia'},
{pais:'República',                                 capital: 'Centroafricana	Bangui' ,                                                       continente:'África'},
{pais:'Chad',                                      capital: 'Yamena' ,                                                                      continente:'África'},
{pais:'República Checa / Chequia',                 capital: 'Praga' ,                                                                       continente:'Europa'},
{pais:'Chile',                                     capital: 'Santiago de Chile8​' ,                                                         continente:'América'},
{pais:'China',                                     capital: 'Pekín' ,                                                                       continente:'Asia'},
{pais:'Chipre',                                    capital: 'Nicosia' ,                                                                     continente:'Europa-Asia'},
{pais:'Colombia',                                  capital: 'Bogotá' ,                                                                      continente:'América'},
{pais:'Comoras',                                   capital: 'Moroni' ,                                                                      continente:'África'},
{pais:'República del Congo',                       capital: 'Brazzaville' ,                                                                 continente:'África'},
{pais:'República Democrática del Congo',           capital: 'Kinsasa' ,                                                                     continente:'África'},
{pais:'Corea',                                     capital: 'del Norte	Pionyang' ,                                                         continente:'Asia'},
{pais:'Corea',                                     capital: 'del Sur	Seúl' ,                                                             continente:'Asia'},
{pais:'Costa',                                     capital: 'de Marfil	Yamusukro10​' ,                                                     continente:'África'},
{pais:'Costa',                                     capital: 'Rica	San José' ,                                                             continente:'América'},
{pais:'Croacia',                                   capital: 'Zagreb' ,                                                                      continente:'Europa'},
{pais:'Cuba',                                      capital: 'La Habana' ,                                                                   continente:'América'},
{pais:'Dinamarca',                                 capital: 'Copenhague' ,                                                                  continente:'Europa'},
{pais:'Dominica',                                  capital: 'Roseau' ,                                                                      continente:'América'},
{pais:'República',                                 capital: 'Dominicana	Santo Domingo' ,                                                    continente:'América'},
{pais:'Ecuador',                                   capital: 'Quito' ,                                                                       continente:'América'},
{pais:'Egipto',                                    capital: 'El Cairo' ,                                                                    continente:'África-Asia'},
{pais:'El Salvador',                               capital: 'San Salvador' ,                                                                continente:'América'},
{pais:'Emiratos Árabes Unidos',                    capital: 'Abu Dabi' ,                                                                    continente:'Asia'},
{pais:'Eritrea',                                   capital: 'Asmara' ,                                                                      continente:'África'},
{pais:'Eslovaquia',                                capital: 'Bratislava' ,                                                                  continente:'Europa'},
{pais:'Eslovenia',                                 capital: 'Liubliana' ,                                                                   continente:'Europa'},
{pais:'España',                                    capital: 'Madrid' ,                                                                      continente:'Europa'},
{pais:'Estados Unidos',                            capital: 'Washington D. C.',                                                             continente:'América'},
{pais:'Estonia',                                   capital: 'Tallin' ,                                                                      continente:'Europa'},
{pais:'Etiopía',                                   capital: 'Adís Abeba' ,                                                                  continente:'África'},
{pais:'Filipinas',                                 capital: 'Manila' ,                                                                      continente:'Asia'},
{pais:'Finlandia',                                 capital: 'Helsinki' ,                                                                    continente:'Europa'},
{pais:'Fiyi',                                      capital: 'Suva' ,                                                                        continente:'Oceanía'},
{pais:'Francia',                                   capital: 'París' ,                                                                       continente:'Europa'},
{pais:'Gabón',                                     capital: 'Libreville' ,                                                                  continente:'África'},
{pais:'Gambia',                                    capital: 'Banjul' ,                                                                      continente:'África'},
{pais:'Georgia',                                   capital: 'Tiflis13​' ,                                                                   continente:'Asia-Europa'},
{pais:'Ghana',                                     capital: 'Acra' ,                                                                        continente:'África'},
{pais:'Granada',                                   capital: 'Saint George' ,                                                                continente:'América'},
{pais:'Grecia',                                    capital: 'Atenas' ,                                                                      continente:'Europa'},
{pais:'Guatemala',                                 capital: 'Ciudad de Guatemala' ,                                                         continente:'América'},
{pais:'Guinea',                                    capital: 'Conakri' ,                                                                     continente:'África'},
{pais:'Guinea-Bisáu',                              capital: 'Bisáu' ,                                                                       continente:'África'},
{pais:'Guinea Ecuatorial',                         capital: 'Malabo' ,                                                                      continente:'África'},
{pais:'Guyana',                                    capital: 'Georgetown' ,                                                                  continente:'América'},
{pais:'Haití',                                     capital: 'Puerto Príncipe' ,                                                             continente:'América'},
{pais:'Honduras',                                  capital: 'Tegucigalpa' ,                                                                 continente:'América'},
{pais:'Hungría',                                   capital: 'Budapest' ,                                                                    continente:'Europa'},
{pais:'India',                                     capital: 'Nueva Delhi' ,                                                                 continente:'Asia'},
{pais:'Indonesia',                                 capital: 'Yakarta' ,                                                                     continente:'Asia'},
{pais:'Irak',                                      capital: 'Bagdad' ,                                                                      continente:'Asia'},
{pais:'Irán',                                      capital: 'Teherán' ,                                                                     continente:'Asia'},
{pais:'Irlanda',                                   capital: 'Dublín' ,                                                                      continente:'Europa'},
{pais:'Islandia',                                  capital: 'Reikiavik' ,                                                                   continente:'Europa'},
{pais:'Israel',                                    capital: 'oficial: Jerusalén15​	de facto: Tel Aviv16​' ,                                continente:'Asia'},
{pais:'Italia',                                    capital: 'Roma' ,                                                                        continente:'Europa'},
{pais:'Jamaica',                                   capital: 'Kingston' ,                                                                    continente:'América'},
{pais:'Japón',                                     capital: 'Tokio' ,                                                                       continente:'Asia'},
{pais:'Jordania',                                  capital: 'Amán' ,                                                                        continente:'Asia'},
{pais:'Kazajistán',                                capital: 'Nursultán' ,                                                                   continente:'Asia-Europa'},
{pais:'Kenia',                                     capital: 'Nairobi' ,                                                                     continente:'África'},
{pais:'Kirguistán',                                capital: 'Biskek' ,                                                                      continente:'Asia'},
{pais:'Kiribati',                                  capital: 'Tarawa Sur' ,                                                                  continente:'Oceanía'},
{pais:'Kuwait',                                    capital: 'Ciudad de Kuwait' ,                                                            continente:'Asia'},
{pais:'Laos',                                      capital: 'Vientián' ,                                                                    continente:'Asia'},
{pais:'Lesoto',                                    capital: 'Maseru' ,                                                                      continente:'África'},
{pais:'Letonia',                                   capital: 'Riga' ,                                                                        continente:'Europa'},
{pais:'Líbano',                                    capital: 'Beirut' ,                                                                      continente:'Asia'},
{pais:'Liberia',                                   capital: 'Monrovia' ,                                                                    continente:'África'},
{pais:'Libia',                                     capital: 'Trípoli' ,                                                                     continente:'África'},
{pais:'Liechtenstein',                             capital: 'Vaduz' ,                                                                       continente:'Europa'},
{pais:'Lituania',                                  capital: 'Vilna' ,                                                                       continente:'Europa'},
{pais:'Luxemburgo',                                capital: 'Ciudad de Luxemburgo' ,                                                        continente:'Europa'},
{pais:'Macedonia del Norte',                       capital: 'Skopie' ,                                                                      continente:'Europa'},
{pais:'Madagascar',                                capital: 'Antananarivo' ,                                                                continente:'África'},
{pais:'Malasia',                                   capital: 'Kuala Lumpur17​' ,                                                             continente:'Asia'},
{pais:'Malaui',                                    capital: 'Lilongüe' ,                                                                    continente:'África'},
{pais:'Maldivas',                                  capital: 'Malé' ,                                                                        continente:'Asia'},
{pais:'Mali / Malí',                               capital: 'Bamako' ,                                                                      continente:'África'},
{pais:'Malta',                                     capital: 'La Valeta' ,                                                                   continente:'Europa'},
{pais:'Marruecos',                                 capital: 'Rabat' ,                                                                       continente:'África'},
{pais:'Islas',                                     capital: 'Marshall	Majuro' ,                                                           continente:'Oceanía'},
{pais:'Mauricio',                                  capital: 'Port Louis' ,                                                                  continente:'África'},
{pais:'Mauritania',                                capital: 'Nuakchot' ,                                                                    continente:'África'},
{pais:'México',                                    capital: 'Ciudad de México' ,                                                            continente:'América'},
{pais:'Micronesia',                                capital: 'Palikir' ,                                                                     continente:'Oceanía'},
{pais:'Moldavia',                                  capital: 'Chisináu' ,                                                                    continente:'Europa'},
{pais:'Mónaco',                                    capital: 'Ciudad de Mónaco' ,                                                            continente:'Europa'},
{pais:'Mongolia',                                  capital: 'Ulán Bator' ,                                                                  continente:'Asia'},
{pais:'Montenegro',                                capital: 'Podgorica' ,                                                                   continente:'Europa'},
{pais:'Mozambique',                                capital: 'Maputo' ,                                                                      continente:'África'},
{pais:'Namibia',                                   capital: 'Windhoek' ,                                                                    continente:'África'},
{pais:'Nauru',                                     capital: 'Yaren19​' ,                                                                    continente:'Oceanía'},
{pais:'Nepal',                                     capital: 'Katmandú' ,                                                                    continente:'Asia'},
{pais:'Nicaragua',                                 capital: 'Managua' ,                                                                     continente:'América'},
{pais:'Níger',                                     capital: 'Niamey' ,                                                                      continente:'África'},
{pais:'Nigeria',                                   capital: 'Abuya' ,                                                                       continente:'África'},
{pais:'Noruega',                                   capital: 'Oslo' ,                                                                        continente:'Europa'},
{pais:'Nueva Zelanda / Nueva Zelandia',            capital: 'Wellington' ,                                                                  continente:'Oceanía'},
{pais:'Omán',                                      capital: 'Mascate' ,                                                                     continente:'Asia'},
{pais:'Países Bajos',                              capital: 'Ámsterdam20​' ,                                                                continente:'Europa'},
{pais:'Pakistán',                                  capital: 'Islamabad' ,                                                                   continente:'Asia'},
{pais:'Palaos',                                    capital: 'Ngerulmud' ,                                                                   continente:'Oceanía'},
{pais:'Palestina',                                 capital: 'oficial: Jerusalén Este	de facto: Ramala' ,                                 continente:'Asia'},
{pais:'Panamá',                                    capital: 'Ciudad de Panamá' ,                                                            continente:'América'},
{pais:'Papúa Nueva Guinea',                        capital: 'Puerto Moresby' ,                                                              continente:'Oceanía'},
{pais:'Paraguay',                                  capital: 'Asunción' ,                                                                    continente:'América'},
{pais:'Perú',                                      capital: 'Lima' ,                                                                        continente:'América'},
{pais:'Polonia',                                   capital: 'Varsovia' ,                                                                    continente:'Europa'},
{pais:'Portugal',                                  capital: 'Lisboa' ,                                                                      continente:'Europa'},
{pais:'Reino',                                     capital: 'Unido	Londres' ,                                                              continente:'Europa'},
{pais:'Ruanda',                                    capital: 'Kigali' ,                                                                      continente:'África'},
{pais:'Rumania / Rumanía',                         capital: 'Bucarest' ,                                                                    continente:'Europa'},
{pais:'Rusia',                                     capital: 'Moscú' ,                                                                       continente:'Europa-Asia'},
{pais:'Islas Salomón',                             capital: 'Honiara' ,                                                                     continente:'Oceanía'},
{pais:'Samoa',                                     capital: 'Apia' ,                                                                        continente:'Oceanía'},
{pais:'San Cristóbal y Nieves',                    capital: 'Basseterre' ,                                                                  continente:'América'},
{pais:'San Marino',                                capital: 'Ciudad de San Marino' ,                                                        continente:'Europa'},
{pais:'San Vicente y las Granadinas',              capital: 'Kingstown' ,                                                                   continente:'América'},
{pais:'Santa Lucía',                               capital: 'Castries' ,                                                                    continente:'América'},
{pais:'Santo Tomé y Príncipe',                     capital: 'Santo Tomé' ,                                                                  continente:'África'},
{pais:'Senegal',                                   capital: 'Dakar' ,                                                                       continente:'África'},
{pais:'Serbia',                                    capital: 'Belgrado' ,                                                                    continente:'Europa'},
{pais:'Seychelles',                                capital: 'Victoria' ,                                                                    continente:'África'},
{pais:'Sierra Leona',                              capital: 'Freetown' ,                                                                    continente:'África'},
{pais:'Singapur',                                  capital: 'Ciudad de Singapur' ,                                                          continente:'Asia'},
{pais:'Siria',                                     capital: 'Damasco' ,                                                                     continente:'Asia'},
{pais:'Somalia',                                   capital: 'Mogadiscio' ,                                                                  continente:'África'},
{pais:'Sri Lanka',                                 capital: 'Sri Jayawardenapura / Kotte​' ,                                                continente:'Asia'},
{pais:'Suazilandia / Esuatini',                    capital: 'Mbabane28​' ,                                                                  continente:'África'},
{pais:'Sudáfrica',                                 capital: 'Pretoria (ejecutiva) Bloemfontein (judicial)	Ciudad del Cabo(legislativa)',  continente:'África'},
{pais:'Sudán',                                     capital: 'Jartum' ,                                                                      continente:'África'},
{pais:'Sudán del Sur',                             capital: 'Yuba' ,                                                                        continente:'África'},
{pais:'Suecia',                                    capital: 'Estocolmo' ,                                                                   continente:'Europa'},
{pais:'Suiza',                                     capital: 'Berna' ,                                                                       continente:'Europa'},
{pais:'Surinam',                                   capital: 'Paramaribo' ,                                                                  continente:'América'},
{pais:'Tailandia',                                 capital: 'Bangkok' ,                                                                     continente:'Asia'},
{pais:'Tanzania',                                  capital: 'Dodoma29​' ,                                                                   continente:'África'},
{pais:'Tayikistán',                                capital: 'Dusambé' ,                                                                     continente:'Asia'},
{pais:'Timor Oriental',                            capital: 'Dili' ,                                                                        continente:'Asia'},
{pais:'Togo',                                      capital: 'Lomé' ,                                                                        continente:'África'},
{pais:'Tonga',                                     capital: 'Nukualofa' ,                                                                   continente:'Oceanía'},
{pais:'Trinidad y Tobago',                         capital: 'Puerto España' ,                                                               continente:'América'},
{pais:'Túnez',                                     capital: 'Ciudad de Túnez' ,                                                             continente:'África'},
{pais:'Turkmenistán',                              capital: 'Asjabad' ,                                                                     continente:'Asia'},
{pais:'Turquía',                                   capital: 'Ankara' ,                                                                      continente:'Asia-Europa'},
{pais:'Tuvalu',                                    capital: 'Funafuti' ,                                                                    continente:'Oceanía'},
{pais:'Ucrania',                                   capital: 'Kiev' ,                                                                        continente:'Europa'},
{pais:'Uganda',                                    capital: 'Kampala' ,                                                                     continente:'África'},
{pais:'Uruguay',                                   capital: 'Montevideo' ,                                                                  continente:'América'},
{pais:'Uzbekistán',                                capital: 'Taskent' ,                                                                     continente:'Asia'},
{pais:'Vanuatu',                                   capital: 'Port Vila' ,                                                                   continente:'Oceanía'},
{pais:'Ciudad del Vaticano',                       capital: 'Ciudad del Vaticano' ,                                                         continente:'Europa'},
{pais:'Venezuela',                                 capital: 'Caracas' ,                                                                     continente:'América'},
{pais:'Vietnam',                                   capital: 'Hanói' ,                                                                       continente:'Asia'},
{pais:'Yemen',                                     capital: 'Saná' ,                                                                        continente:'Asia'},
{pais:'Yibuti',                                    capital: 'Ciudad de Yibuti' ,                                                            continente:'África'},
{pais:'Zambia',                                    capital: 'Lusaka' ,                                                                      continente:'África'},
{pais:'Zimbabue',                                  capital: 'Harare' ,                                                                      continente:'África'}];